// Objective-C API for talking to github.com/mpiannucci/HackWinds-Data Go package.
//   gobind -lang=objc github.com/mpiannucci/HackWinds-Data
//
// File is generated by gobind. Do not edit.

#ifndef __GoHackwindsdata_H__
#define __GoHackwindsdata_H__

#include <Foundation/Foundation.h>

@class GoHackwindsdataBuoy;

@class GoHackwindsdataCamera;

@class GoHackwindsdataCondition;

@class GoHackwindsdataForecast;

@class GoHackwindsdataTide;

@class GoHackwindsdataTideModel;

@interface GoHackwindsdataBuoy : NSObject {
}
@property(strong, readonly) id ref;

- (id)initWithRef:(id)ref;
- (NSString*)Time;
- (void)setTime:(NSString*)v;
- (NSString*)WaveHeight;
- (void)setWaveHeight:(NSString*)v;
- (NSString*)DominantPeriod;
- (void)setDominantPeriod:(NSString*)v;
- (NSString*)SwellDirection;
- (void)setSwellDirection:(NSString*)v;
- (NSString*)WaterTemperature;
- (void)setWaterTemperature:(NSString*)v;
@end

@interface GoHackwindsdataCamera : NSObject {
}
@property(strong, readonly) id ref;

- (id)initWithRef:(id)ref;
- (NSString*)ImageURL;
- (void)setImageURL:(NSString*)v;
- (NSString*)VideoURL;
- (void)setVideoURL:(NSString*)v;
- (NSString*)ExtraInfo;
- (void)setExtraInfo:(NSString*)v;
@end

@interface GoHackwindsdataCondition : NSObject {
}
@property(strong, readonly) id ref;

- (id)initWithRef:(id)ref;
- (GoHackwindsdataForecast*)Forecast;
- (void)setForecast:(GoHackwindsdataForecast*)v;
- (NSString*)WindDeg;
- (void)setWindDeg:(NSString*)v;
- (NSString*)SwellHeight;
- (void)setSwellHeight:(NSString*)v;
- (NSString*)SwellPeriod;
- (void)setSwellPeriod:(NSString*)v;
- (NSString*)SwellDirection;
- (void)setSwellDirection:(NSString*)v;
- (NSString*)SwellChartURL;
- (void)setSwellChartURL:(NSString*)v;
- (NSString*)WindChartURL;
- (void)setWindChartURL:(NSString*)v;
- (NSString*)PeriodChartURL;
- (void)setPeriodChartURL:(NSString*)v;
@end

@interface GoHackwindsdataForecast : NSObject {
}
@property(strong, readonly) id ref;

- (id)initWithRef:(id)ref;
- (NSString*)Date;
- (void)setDate:(NSString*)v;
- (NSString*)MinBreakingHeight;
- (void)setMinBreakingHeight:(NSString*)v;
- (NSString*)MaxBreakingHeight;
- (void)setMaxBreakingHeight:(NSString*)v;
- (NSString*)WindSpeed;
- (void)setWindSpeed:(NSString*)v;
- (NSString*)WindDirection;
- (void)setWindDirection:(NSString*)v;
@end

@interface GoHackwindsdataTide : NSObject {
}
@property(strong, readonly) id ref;

- (id)initWithRef:(id)ref;
- (NSString*)Time;
- (void)setTime:(NSString*)v;
- (NSString*)EventType;
- (void)setEventType:(NSString*)v;
- (NSString*)Height;
- (void)setHeight:(NSString*)v;
@end

@interface GoHackwindsdataTideModel : NSObject {
}
@property(strong, readonly) id ref;

- (id)initWithRef:(id)ref;
- (int)TideCount;
- (void)setTideCount:(int)v;
- (BOOL)FetchTideData;
- (GoHackwindsdataTide*)GetTideEventForIndex:(int)index;
@end

FOUNDATION_EXPORT void GoHackwindsdataHi();

FOUNDATION_EXPORT GoHackwindsdataBuoy* GoHackwindsdataNewBuoy(NSString* time, NSString* waveHeight, NSString* dominantPeriod, NSString* swellDirection, NSString* waterTemperature);

FOUNDATION_EXPORT GoHackwindsdataCamera* GoHackwindsdataNewCamera(NSString* imageURL, NSString* info);

FOUNDATION_EXPORT GoHackwindsdataCamera* GoHackwindsdataNewCameraWithVideo(NSString* imageURL, NSString* videoURL, NSString* info);

FOUNDATION_EXPORT GoHackwindsdataCondition* GoHackwindsdataNewCondition(GoHackwindsdataForecast* forecast, NSString* windDeg, NSString* swellHeight, NSString* swellPeriod, NSString* swellDirection, NSString* swellChartURL, NSString* windChartURL, NSString* periodChartURL);

FOUNDATION_EXPORT GoHackwindsdataForecast* GoHackwindsdataNewForecast(NSString* date, NSString* minBreakHeight, NSString* maxBreakHeight, NSString* windSpeed, NSString* windDirection);

FOUNDATION_EXPORT GoHackwindsdataTide* GoHackwindsdataNewTide(NSString* time, NSString* eventType, NSString* height);

FOUNDATION_EXPORT GoHackwindsdataTideModel* GoHackwindsdataNewTideModel();

FOUNDATION_EXPORT BOOL GoHackwindsdataValidateTideEvent(NSString* event);

#endif
