// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   camera/v1
// Description:
//   This is an API

#import <GoogleAPIClientForREST/GTLRObject.h>

#if GTLR_RUNTIME_VERSION != 3000
#error This file was generated by a different version of ServiceGenerator which is incompatible with this GTLR library source.
#endif

@class GTLRCamera_ModelCameraMessagesCameraMessage;
@class GTLRCamera_ModelCameraMessagesCameraRegionMessage;

// Generated comments include content from the discovery document; avoid them
// causing warnings since clang's checks are some what arbitrary.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdocumentation"

NS_ASSUME_NONNULL_BEGIN

// ----------------------------------------------------------------------------
// Constants - For some of the classes' properties below.

// ----------------------------------------------------------------------------
// GTLRCamera_ModelCameraMessagesCameraMessage.refreshMethod

/** Value: "NONE" */
GTLR_EXTERN NSString * const kGTLRCamera_ModelCameraMessagesCameraMessage_RefreshMethod_None;
/** Value: "SEQUENTIAL" */
GTLR_EXTERN NSString * const kGTLRCamera_ModelCameraMessagesCameraMessage_RefreshMethod_Sequential;
/** Value: "STATIC" */
GTLR_EXTERN NSString * const kGTLRCamera_ModelCameraMessagesCameraMessage_RefreshMethod_Static;

/**
 *  GTLRCamera_ModelCameraMessagesCameraLocationsMessage
 */
@interface GTLRCamera_ModelCameraMessagesCameraLocationsMessage : GTLRObject

@property(nonatomic, strong, nullable) NSArray<GTLRCamera_ModelCameraMessagesCameraRegionMessage *> *cameraLocations;

@end


/**
 *  GTLRCamera_ModelCameraMessagesCameraMessage
 */
@interface GTLRCamera_ModelCameraMessagesCameraMessage : GTLRObject

@property(nonatomic, copy, nullable) NSString *imageUrl;
@property(nonatomic, copy, nullable) NSString *info;
@property(nonatomic, copy, nullable) NSString *name;

/**
 *  premium
 *
 *  Uses NSNumber of boolValue.
 */
@property(nonatomic, strong, nullable) NSNumber *premium;

/**
 *  refreshInterval
 *
 *  Uses NSNumber of longLongValue.
 */
@property(nonatomic, strong, nullable) NSNumber *refreshInterval;

/**
 *  refreshMethod
 *
 *  Likely values:
 *    @arg @c kGTLRCamera_ModelCameraMessagesCameraMessage_RefreshMethod_None
 *        Value "NONE"
 *    @arg @c kGTLRCamera_ModelCameraMessagesCameraMessage_RefreshMethod_Sequential
 *        Value "SEQUENTIAL"
 *    @arg @c kGTLRCamera_ModelCameraMessagesCameraMessage_RefreshMethod_Static
 *        Value "STATIC"
 */
@property(nonatomic, copy, nullable) NSString *refreshMethod;

/**
 *  refreshable
 *
 *  Uses NSNumber of boolValue.
 */
@property(nonatomic, strong, nullable) NSNumber *refreshable;

@property(nonatomic, copy, nullable) NSString *videoUrl;
@property(nonatomic, copy, nullable) NSString *webUrl;

@end


/**
 *  GTLRCamera_ModelCameraMessagesCameraRegionMessage
 */
@interface GTLRCamera_ModelCameraMessagesCameraRegionMessage : GTLRObject

@property(nonatomic, strong, nullable) NSArray<GTLRCamera_ModelCameraMessagesCameraMessage *> *cameras;
@property(nonatomic, copy, nullable) NSString *name;

@end

NS_ASSUME_NONNULL_END

#pragma clang diagnostic pop
