// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   camera/v1
// Description:
//   This is an API

#import "GTLRCameraObjects.h"

// ----------------------------------------------------------------------------
// Constants

// GTLRCamera_ModelCameraMessagesCameraMessage.refreshMethod
NSString * const kGTLRCamera_ModelCameraMessagesCameraMessage_RefreshMethod_None = @"NONE";
NSString * const kGTLRCamera_ModelCameraMessagesCameraMessage_RefreshMethod_Sequential = @"SEQUENTIAL";
NSString * const kGTLRCamera_ModelCameraMessagesCameraMessage_RefreshMethod_Static = @"STATIC";

// ----------------------------------------------------------------------------
//
//   GTLRCamera_ModelCameraMessagesCameraLocationsMessage
//

@implementation GTLRCamera_ModelCameraMessagesCameraLocationsMessage
@dynamic cameraLocations;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"cameraLocations" : @"camera_locations" };
}

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"camera_locations" : [GTLRCamera_ModelCameraMessagesCameraRegionMessage class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRCamera_ModelCameraMessagesCameraMessage
//

@implementation GTLRCamera_ModelCameraMessagesCameraMessage
@dynamic imageUrl, info, name, premium, refreshInterval, refreshMethod,
         refreshable, videoUrl, webUrl;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  NSDictionary<NSString *, NSString *> *map = @{
    @"imageUrl" : @"image_url",
    @"refreshInterval" : @"refresh_interval",
    @"refreshMethod" : @"refresh_method",
    @"videoUrl" : @"video_url",
    @"webUrl" : @"web_url"
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRCamera_ModelCameraMessagesCameraRegionMessage
//

@implementation GTLRCamera_ModelCameraMessagesCameraRegionMessage
@dynamic cameras, name;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"cameras" : [GTLRCamera_ModelCameraMessagesCameraMessage class]
  };
  return map;
}

@end
