// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   station/v1
// Description:
//   This is an API

#import "GTLRStation.h"

// ----------------------------------------------------------------------------
// Authorization scope

NSString * const kGTLRAuthScopeStationUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";

// ----------------------------------------------------------------------------
//   GTLRStationService
//

@implementation GTLRStationService

- (instancetype)init {
  self = [super init];
  if (self) {
    // From discovery.
    self.rootURLString = @"https://mpitester-13.appspot.com/_ah/api/";
    self.servicePath = @"station/v1/";
    self.batchPath = @"batch";
    self.prettyPrintQueryParameterNames = @[ @"prettyPrint" ];
  }
  return self;
}

@end
