// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   camera/v1
// Description:
//   This is an API

#import "GTLRCameraQuery.h"

#import "GTLRCameraObjects.h"

@implementation GTLRCameraQuery

@dynamic fields;

@end

@implementation GTLRCameraQuery_Cameras

@dynamic premium;

+ (instancetype)queryWithPremium:(BOOL)premium {
  NSString *pathURITemplate = @"cameras";
  GTLRCameraQuery_Cameras *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:nil
                       pathParameterNames:nil];
  query.premium = premium;
  query.expectedObjectClass = [GTLRCamera_ModelCameraMessagesCameraLocationsMessage class];
  query.loggingName = @"camera.cameras";
  return query;
}

@end
