// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   camera/v1
// Description:
//   This is an API

#import "GTLRCameraObjects.h"
#import "GTLRCameraQuery.h"
#import "GTLRCameraService.h"
