// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   station/v1
// Description:
//   This is an API

#import <GoogleAPIClientForREST/GTLRObject.h>

#if GTLR_RUNTIME_VERSION != 3000
#error This file was generated by a different version of ServiceGenerator which is incompatible with this GTLR library source.
#endif

@class GTLRStation_ApiApiMessagesDataMessage;
@class GTLRStation_ApiApiMessagesLocationMessage;
@class GTLRStation_ApiApiMessagesMeasurementLabelMessage;
@class GTLRStation_ApiApiMessagesStationMessage;
@class GTLRStation_ApiApiMessagesSwellMessage;
@class GTLRStation_ApiApiMessagesUnitLabelMessage;
@class GTLRStation_ApiApiMessagesWaveSpectraMessage;

// Generated comments include content from the discovery document; avoid them
// causing warnings since clang's checks are some what arbitrary.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdocumentation"

NS_ASSUME_NONNULL_BEGIN

// ----------------------------------------------------------------------------
// Constants - For some of the classes' properties below.

// ----------------------------------------------------------------------------
// GTLRStation_ApiApiMessagesMeasurementLabelMessage.measurement

/** Value: "DIRECTION" */
GTLR_EXTERN NSString * const kGTLRStation_ApiApiMessagesMeasurementLabelMessage_Measurement_Direction;
/** Value: "LENGTH" */
GTLR_EXTERN NSString * const kGTLRStation_ApiApiMessagesMeasurementLabelMessage_Measurement_Length;
/** Value: "PRESSURE" */
GTLR_EXTERN NSString * const kGTLRStation_ApiApiMessagesMeasurementLabelMessage_Measurement_Pressure;
/** Value: "SPEED" */
GTLR_EXTERN NSString * const kGTLRStation_ApiApiMessagesMeasurementLabelMessage_Measurement_Speed;
/** Value: "TEMPERATURE" */
GTLR_EXTERN NSString * const kGTLRStation_ApiApiMessagesMeasurementLabelMessage_Measurement_Temperature;
/** Value: "VISIBILITY" */
GTLR_EXTERN NSString * const kGTLRStation_ApiApiMessagesMeasurementLabelMessage_Measurement_Visibility;

// ----------------------------------------------------------------------------
// GTLRStation_ApiApiMessagesUnitLabelMessage.unit

/** Value: "ENGLISH" */
GTLR_EXTERN NSString * const kGTLRStation_ApiApiMessagesUnitLabelMessage_Unit_English;
/** Value: "METRIC" */
GTLR_EXTERN NSString * const kGTLRStation_ApiApiMessagesUnitLabelMessage_Unit_Metric;

/**
 *  GTLRStation_ApiApiMessagesDataMessage
 */
@interface GTLRStation_ApiApiMessagesDataMessage : GTLRObject

/**
 *  airTemperature
 *
 *  Uses NSNumber of doubleValue.
 */
@property(nonatomic, strong, nullable) NSNumber *airTemperature;

/**
 *  averagePeriod
 *
 *  Uses NSNumber of doubleValue.
 */
@property(nonatomic, strong, nullable) NSNumber *averagePeriod;

@property(nonatomic, strong, nullable) GTLRDateTime *date;

/**
 *  dewpointTemperature
 *
 *  Uses NSNumber of doubleValue.
 */
@property(nonatomic, strong, nullable) NSNumber *dewpointTemperature;

@property(nonatomic, copy, nullable) NSString *directionSpectraPlot;
@property(nonatomic, copy, nullable) NSString *energySpectraPlot;

/**
 *  pressure
 *
 *  Uses NSNumber of doubleValue.
 */
@property(nonatomic, strong, nullable) NSNumber *pressure;

/**
 *  pressureTendency
 *
 *  Uses NSNumber of doubleValue.
 */
@property(nonatomic, strong, nullable) NSNumber *pressureTendency;

@property(nonatomic, copy, nullable) NSString *steepness;
@property(nonatomic, strong, nullable) NSArray<GTLRStation_ApiApiMessagesSwellMessage *> *swellComponents;
@property(nonatomic, strong, nullable) GTLRStation_ApiApiMessagesUnitLabelMessage *units;

/**
 *  waterLevel
 *
 *  Uses NSNumber of doubleValue.
 */
@property(nonatomic, strong, nullable) NSNumber *waterLevel;

/**
 *  waterTemperature
 *
 *  Uses NSNumber of doubleValue.
 */
@property(nonatomic, strong, nullable) NSNumber *waterTemperature;

@property(nonatomic, strong, nullable) GTLRStation_ApiApiMessagesWaveSpectraMessage *waveSpectra;
@property(nonatomic, strong, nullable) GTLRStation_ApiApiMessagesSwellMessage *waveSummary;
@property(nonatomic, copy, nullable) NSString *windCompassDirection;

/**
 *  windDirection
 *
 *  Uses NSNumber of doubleValue.
 */
@property(nonatomic, strong, nullable) NSNumber *windDirection;

/**
 *  windGust
 *
 *  Uses NSNumber of doubleValue.
 */
@property(nonatomic, strong, nullable) NSNumber *windGust;

/**
 *  windSpeed
 *
 *  Uses NSNumber of doubleValue.
 */
@property(nonatomic, strong, nullable) NSNumber *windSpeed;

@end


/**
 *  GTLRStation_ApiApiMessagesLocationMessage
 */
@interface GTLRStation_ApiApiMessagesLocationMessage : GTLRObject

/**
 *  altitude
 *
 *  Uses NSNumber of doubleValue.
 */
@property(nonatomic, strong, nullable) NSNumber *altitude;

/**
 *  latitude
 *
 *  Uses NSNumber of doubleValue.
 */
@property(nonatomic, strong, nullable) NSNumber *latitude;

/**
 *  longitude
 *
 *  Uses NSNumber of doubleValue.
 */
@property(nonatomic, strong, nullable) NSNumber *longitude;

@property(nonatomic, copy, nullable) NSString *name;

@end


/**
 *  GTLRStation_ApiApiMessagesMeasurementLabelMessage
 */
@interface GTLRStation_ApiApiMessagesMeasurementLabelMessage : GTLRObject

@property(nonatomic, copy, nullable) NSString *label;

/**
 *  measurement
 *
 *  Likely values:
 *    @arg @c kGTLRStation_ApiApiMessagesMeasurementLabelMessage_Measurement_Direction
 *        Value "DIRECTION"
 *    @arg @c kGTLRStation_ApiApiMessagesMeasurementLabelMessage_Measurement_Length
 *        Value "LENGTH"
 *    @arg @c kGTLRStation_ApiApiMessagesMeasurementLabelMessage_Measurement_Pressure
 *        Value "PRESSURE"
 *    @arg @c kGTLRStation_ApiApiMessagesMeasurementLabelMessage_Measurement_Speed
 *        Value "SPEED"
 *    @arg @c kGTLRStation_ApiApiMessagesMeasurementLabelMessage_Measurement_Temperature
 *        Value "TEMPERATURE"
 *    @arg @c kGTLRStation_ApiApiMessagesMeasurementLabelMessage_Measurement_Visibility
 *        Value "VISIBILITY"
 */
@property(nonatomic, copy, nullable) NSString *measurement;

@end


/**
 *  GTLRStation_ApiApiMessagesPlotMessage
 */
@interface GTLRStation_ApiApiMessagesPlotMessage : GTLRObject

/**
 *  plot
 *
 *  Contains encoded binary data; GTLRBase64 can encode/decode (probably
 *  web-safe format).
 */
@property(nonatomic, copy, nullable) NSString *plot;

@property(nonatomic, copy, nullable) NSString *stationId;

@end


/**
 *  GTLRStation_ApiApiMessagesStationMessage
 */
@interface GTLRStation_ApiApiMessagesStationMessage : GTLRObject

/**
 *  active
 *
 *  Uses NSNumber of boolValue.
 */
@property(nonatomic, strong, nullable) NSNumber *active;

/**
 *  currents
 *
 *  Uses NSNumber of boolValue.
 */
@property(nonatomic, strong, nullable) NSNumber *currents;

/**
 *  dart
 *
 *  Uses NSNumber of boolValue.
 */
@property(nonatomic, strong, nullable) NSNumber *dart;

@property(nonatomic, strong, nullable) NSArray<GTLRStation_ApiApiMessagesDataMessage *> *data;
@property(nonatomic, strong, nullable) GTLRStation_ApiApiMessagesLocationMessage *location;
@property(nonatomic, copy, nullable) NSString *name;
@property(nonatomic, copy, nullable) NSString *owner;
@property(nonatomic, copy, nullable) NSString *program;
@property(nonatomic, copy, nullable) NSString *stationId;
@property(nonatomic, copy, nullable) NSString *stationType;

/**
 *  waterQuality
 *
 *  Uses NSNumber of boolValue.
 */
@property(nonatomic, strong, nullable) NSNumber *waterQuality;

@end


/**
 *  GTLRStation_ApiApiMessagesStationsMessage
 */
@interface GTLRStation_ApiApiMessagesStationsMessage : GTLRObject

@property(nonatomic, strong, nullable) GTLRDateTime *fetchDate;
@property(nonatomic, strong, nullable) NSArray<GTLRStation_ApiApiMessagesStationMessage *> *stations;

@end


/**
 *  GTLRStation_ApiApiMessagesSwellMessage
 */
@interface GTLRStation_ApiApiMessagesSwellMessage : GTLRObject

@property(nonatomic, copy, nullable) NSString *compassDirection;

/**
 *  direction
 *
 *  Uses NSNumber of doubleValue.
 */
@property(nonatomic, strong, nullable) NSNumber *direction;

/**
 *  period
 *
 *  Uses NSNumber of doubleValue.
 */
@property(nonatomic, strong, nullable) NSNumber *period;

@property(nonatomic, strong, nullable) GTLRStation_ApiApiMessagesUnitLabelMessage *unit;

/**
 *  waveHeight
 *
 *  Uses NSNumber of doubleValue.
 */
@property(nonatomic, strong, nullable) NSNumber *waveHeight;

@end


/**
 *  GTLRStation_ApiApiMessagesUnitLabelMessage
 */
@interface GTLRStation_ApiApiMessagesUnitLabelMessage : GTLRObject

@property(nonatomic, strong, nullable) NSArray<GTLRStation_ApiApiMessagesMeasurementLabelMessage *> *measurements;

/**
 *  unit
 *
 *  Likely values:
 *    @arg @c kGTLRStation_ApiApiMessagesUnitLabelMessage_Unit_English Value
 *        "ENGLISH"
 *    @arg @c kGTLRStation_ApiApiMessagesUnitLabelMessage_Unit_Metric Value
 *        "METRIC"
 */
@property(nonatomic, copy, nullable) NSString *unit;

@end


/**
 *  GTLRStation_ApiApiMessagesWaveSpectraMessage
 */
@interface GTLRStation_ApiApiMessagesWaveSpectraMessage : GTLRObject

/**
 *  angle
 *
 *  Uses NSNumber of doubleValue.
 */
@property(nonatomic, strong, nullable) NSArray<NSNumber *> *angle;

/**
 *  energy
 *
 *  Uses NSNumber of doubleValue.
 */
@property(nonatomic, strong, nullable) NSArray<NSNumber *> *energy;

/**
 *  frequency
 *
 *  Uses NSNumber of doubleValue.
 */
@property(nonatomic, strong, nullable) NSArray<NSNumber *> *frequency;

/**
 *  seperationFrequency
 *
 *  Uses NSNumber of doubleValue.
 */
@property(nonatomic, strong, nullable) NSNumber *seperationFrequency;

@end

NS_ASSUME_NONNULL_END

#pragma clang diagnostic pop
