// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   station/v1
// Description:
//   This is an API

#import <GoogleAPIClientForREST/GTLRQuery.h>

#if GTLR_RUNTIME_VERSION != 3000
#error This file was generated by a different version of ServiceGenerator which is incompatible with this GTLR library source.
#endif

// Generated comments include content from the discovery document; avoid them
// causing warnings since clang's checks are some what arbitrary.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdocumentation"

NS_ASSUME_NONNULL_BEGIN

// ----------------------------------------------------------------------------
// Constants - For some of the query classes' properties below.

// ----------------------------------------------------------------------------
// buoyType

/** Value: "BUOY" */
GTLR_EXTERN NSString * const kGTLRStationBuoyTypeBuoy;
/** Value: "DART" */
GTLR_EXTERN NSString * const kGTLRStationBuoyTypeDart;
/** Value: "FIXED" */
GTLR_EXTERN NSString * const kGTLRStationBuoyTypeFixed;
/** Value: "NONE" */
GTLR_EXTERN NSString * const kGTLRStationBuoyTypeNone;
/** Value: "OILRIG" */
GTLR_EXTERN NSString * const kGTLRStationBuoyTypeOilrig;
/** Value: "OTHER" */
GTLR_EXTERN NSString * const kGTLRStationBuoyTypeOther;
/** Value: "TAO" */
GTLR_EXTERN NSString * const kGTLRStationBuoyTypeTao;

// ----------------------------------------------------------------------------
// dataType

/** Value: "SPECTRA" */
GTLR_EXTERN NSString * const kGTLRStationDataTypeSpectra;
/** Value: "WAVES" */
GTLR_EXTERN NSString * const kGTLRStationDataTypeWaves;
/** Value: "WEATHER" */
GTLR_EXTERN NSString * const kGTLRStationDataTypeWeather;

// ----------------------------------------------------------------------------
// plotType

/** Value: "DIRECTION" */
GTLR_EXTERN NSString * const kGTLRStationPlotTypeDirection;
/** Value: "ENERGY" */
GTLR_EXTERN NSString * const kGTLRStationPlotTypeEnergy;

// ----------------------------------------------------------------------------
// units

/** Value: "ENGLISH" */
GTLR_EXTERN NSString * const kGTLRStationUnitsEnglish;
/** Value: "METRIC" */
GTLR_EXTERN NSString * const kGTLRStationUnitsMetric;

// ----------------------------------------------------------------------------
// Query Classes
//

/**
 *  Parent class for other Station query classes.
 */
@interface GTLRStationQuery : GTLRQuery

/** Selector specifying which fields to include in a partial response. */
@property(nonatomic, copy, nullable) NSString *fields;

@end

/**
 *  GTLRStationQuery_ClosestStation
 *
 *  Method: station.closest_station
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeStationUserinfoEmail
 */
@interface GTLRStationQuery_ClosestStation : GTLRStationQuery
// Previous library name was
//   +[GTLQueryStation queryForClosestStationWithactive:count:latitude:longitude:buoyType:]

@property(nonatomic, assign) BOOL active;

/**
 *  buoyType
 *
 *  Likely values:
 *    @arg @c kGTLRStationBuoyTypeBuoy Value "BUOY"
 *    @arg @c kGTLRStationBuoyTypeDart Value "DART"
 *    @arg @c kGTLRStationBuoyTypeFixed Value "FIXED"
 *    @arg @c kGTLRStationBuoyTypeNone Value "NONE"
 *    @arg @c kGTLRStationBuoyTypeOilrig Value "OILRIG"
 *    @arg @c kGTLRStationBuoyTypeOther Value "OTHER"
 *    @arg @c kGTLRStationBuoyTypeTao Value "TAO"
 *
 *  @note If not set, the documented server-side default will be
 *        kGTLRStationBuoyTypeBuoy.
 */
@property(nonatomic, copy, nullable) NSString *buoyType;

/**
 *  count
 *
 *  @note If not set, the documented server-side default will be 1.
 */
@property(nonatomic, assign) long long count;

@property(nonatomic, assign) double latitude;

@property(nonatomic, assign) double longitude;

/**
 *  Fetches a @c GTLRStation_ApiApiMessagesStationMessage.
 *
 *  @param active BOOL
 *  @param count Default 1
 *  @param latitude double
 *  @param longitude double
 *  @param buoyType Default kGTLRStationBuoyTypeBuoy
 *
 *  Likely values for @c buoyType:
 *    @arg @c kGTLRStationBuoyTypeBuoy Value "BUOY"
 *    @arg @c kGTLRStationBuoyTypeDart Value "DART"
 *    @arg @c kGTLRStationBuoyTypeFixed Value "FIXED"
 *    @arg @c kGTLRStationBuoyTypeNone Value "NONE"
 *    @arg @c kGTLRStationBuoyTypeOilrig Value "OILRIG"
 *    @arg @c kGTLRStationBuoyTypeOther Value "OTHER"
 *    @arg @c kGTLRStationBuoyTypeTao Value "TAO"
 *
 *  @returns GTLRStationQuery_ClosestStation
 */
+ (instancetype)queryWithActive:(BOOL)active
                          count:(long long)count
                       latitude:(double)latitude
                      longitude:(double)longitude
                       buoyType:(NSString *)buoyType;

@end

/**
 *  GTLRStationQuery_Data
 *
 *  Method: station.data
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeStationUserinfoEmail
 */
@interface GTLRStationQuery_Data : GTLRStationQuery
// Previous library name was
//   +[GTLQueryStation queryForDataWithunits:stationId:]

/**
 *  dataType
 *
 *  Likely values:
 *    @arg @c kGTLRStationDataTypeSpectra Value "SPECTRA"
 *    @arg @c kGTLRStationDataTypeWaves Value "WAVES"
 *    @arg @c kGTLRStationDataTypeWeather Value "WEATHER"
 */
@property(nonatomic, copy, nullable) NSString *dataType;

@property(nonatomic, copy, nullable) NSString *stationId;

/**
 *  units
 *
 *  Likely values:
 *    @arg @c kGTLRStationUnitsEnglish Value "ENGLISH"
 *    @arg @c kGTLRStationUnitsMetric Value "METRIC"
 *
 *  @note If not set, the documented server-side default will be
 *        kGTLRStationUnitsMetric.
 */
@property(nonatomic, copy, nullable) NSString *units;

@property(nonatomic, assign) long long whenMilliseconds;

@property(nonatomic, assign) long long whenTimeZoneOffset;

/**
 *  Fetches a @c GTLRStation_ApiApiMessagesDataMessage.
 *
 *  @param units Default kGTLRStationUnitsMetric
 *  @param stationId NSString
 *
 *  Likely values for @c units:
 *    @arg @c kGTLRStationUnitsEnglish Value "ENGLISH"
 *    @arg @c kGTLRStationUnitsMetric Value "METRIC"
 *
 *  @returns GTLRStationQuery_Data
 */
+ (instancetype)queryWithUnits:(NSString *)units
                     stationId:(NSString *)stationId;

@end

/**
 *  GTLRStationQuery_Info
 *
 *  Method: station.info
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeStationUserinfoEmail
 */
@interface GTLRStationQuery_Info : GTLRStationQuery
// Previous library name was
//   +[GTLQueryStation queryForInfoWithstationId:]

@property(nonatomic, copy, nullable) NSString *stationId;

/**
 *  Fetches a @c GTLRStation_ApiApiMessagesStationMessage.
 *
 *  @param stationId NSString
 *
 *  @returns GTLRStationQuery_Info
 */
+ (instancetype)queryWithStationId:(NSString *)stationId;

@end

/**
 *  GTLRStationQuery_Plot
 *
 *  Method: station.plot
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeStationUserinfoEmail
 */
@interface GTLRStationQuery_Plot : GTLRStationQuery
// Previous library name was
//   +[GTLQueryStation queryForPlotWithplotType:stationId:]

/**
 *  plotType
 *
 *  Likely values:
 *    @arg @c kGTLRStationPlotTypeDirection Value "DIRECTION"
 *    @arg @c kGTLRStationPlotTypeEnergy Value "ENERGY"
 */
@property(nonatomic, copy, nullable) NSString *plotType;

@property(nonatomic, copy, nullable) NSString *stationId;

/**
 *  Fetches a @c GTLRStation_ApiApiMessagesPlotMessage.
 *
 *  @param plotType NSString
 *  @param stationId NSString
 *
 *  Likely values for @c plotType:
 *    @arg @c kGTLRStationPlotTypeDirection Value "DIRECTION"
 *    @arg @c kGTLRStationPlotTypeEnergy Value "ENERGY"
 *
 *  @returns GTLRStationQuery_Plot
 */
+ (instancetype)queryWithPlotType:(NSString *)plotType
                        stationId:(NSString *)stationId;

@end

/**
 *  GTLRStationQuery_Stations
 *
 *  Method: station.stations
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeStationUserinfoEmail
 */
@interface GTLRStationQuery_Stations : GTLRStationQuery
// Previous library name was
//   +[GTLQueryStation queryForStations]

/**
 *  Fetches a @c GTLRStation_ApiApiMessagesStationsMessage.
 *
 *  @returns GTLRStationQuery_Stations
 */
+ (instancetype)query;

@end

/**
 *  GTLRStationQuery_UnitLabels
 *
 *  Method: station.unit_labels
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeStationUserinfoEmail
 */
@interface GTLRStationQuery_UnitLabels : GTLRStationQuery
// Previous library name was
//   +[GTLQueryStation queryForUnitLabelsWithunits:abbrev:]

/**
 *  abbrev
 *
 *  @note If not set, the documented server-side default will be true.
 */
@property(nonatomic, assign) BOOL abbrev;

/**
 *  units
 *
 *  Likely values:
 *    @arg @c kGTLRStationUnitsEnglish Value "ENGLISH"
 *    @arg @c kGTLRStationUnitsMetric Value "METRIC"
 */
@property(nonatomic, copy, nullable) NSString *units;

/**
 *  Fetches a @c GTLRStation_ApiApiMessagesUnitLabelMessage.
 *
 *  @param units NSString
 *  @param abbrev Default true
 *
 *  Likely values for @c units:
 *    @arg @c kGTLRStationUnitsEnglish Value "ENGLISH"
 *    @arg @c kGTLRStationUnitsMetric Value "METRIC"
 *
 *  @returns GTLRStationQuery_UnitLabels
 */
+ (instancetype)queryWithUnits:(NSString *)units
                        abbrev:(BOOL)abbrev;

@end

NS_ASSUME_NONNULL_END

#pragma clang diagnostic pop
