// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   hackwinds/v1
// Description:
//   This is an API

#import "GTLRHackwindsQuery.h"

#import "GTLRHackwindsObjects.h"

@implementation GTLRHackwindsQuery

@dynamic fields;

@end

@implementation GTLRHackwindsQuery_CameraCameras

@dynamic premium;

+ (instancetype)queryWithPremium:(BOOL)premium {
  NSString *pathURITemplate = @"camera/cameras";
  GTLRHackwindsQuery_CameraCameras *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:nil
                       pathParameterNames:nil];
  query.premium = premium;
  query.expectedObjectClass = [GTLRHackwinds_ModelCameraMessagesCameraLocationsMessage class];
  query.loggingName = @"hackwinds.camera.cameras";
  return query;
}

@end

@implementation GTLRHackwindsQuery_ForecastForecast

+ (instancetype)query {
  NSString *pathURITemplate = @"forecast/forecast";
  GTLRHackwindsQuery_ForecastForecast *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:nil
                       pathParameterNames:nil];
  query.expectedObjectClass = [GTLRHackwinds_ModelForecastMessagesSurfForecastMessage class];
  query.loggingName = @"hackwinds.forecast.forecast";
  return query;
}

@end
